sudo: required
language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - docker
after_success:
  - docker build -t myrepo .
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker tag myrepo:latest 462721059819.dkr.ecr.us-east-1.amazonaws.com/myrepor:petclinic
  - docker push 462721059819.dkr.ecr.us-east-1.amazonaws.com/myrepor:petclinic
  - aws ecs run-task --cluster default --region us-east-1 --task-definition petclinic:1
